language: go

go:
  - 1.x

addons:
  apt:
    packages:
    - upx-ucl

before_install:
  - go get github.com/mitchellh/gox

after_success:
  - gox -arch="amd64" -os="windows linux darwin"
  - ls -lhR

deploy:
  provider: releases
  api_key:
    secure: YDvNaVFyi1cq/IiKox5SsBEIznaOD0truWQIQFpetqQFr3/d3tcmLrJ+gaqXAcb5kUbP3NzUo7lTi2IgsFX9KDZA1o4FfcRXQeLmKLUzhEKpe2urbfKSrN66+Vmb+c0VR0PUU1ckhrKQ5mNLQoxcn/vtXxeF87uFNtGE5kGJtgxoVRqIRMMOL4QEH6q2La5laLncK4N4/VmIFFPIpjiuHf/bryGeHzkMjx2eHSLvADQYlRcJX9H4jWgmTBik7ieaSXwpVZwSURFsR167yssTgiyq5w4gFRlU+S9Zeo22KyUXgmtmLioTNDXj4w8FEs6W7JngYFyUMpEfSPvzP8CwuyNI7Bj6vJfy02VZdMbiHK9V2P8Ugm8ce4TuKT7SpZR8GEMjF/fKVcCBiB4GNenvOwqvyWyqoRDMu5OrB23Ca1vgiaSETkDRaZ72ShGqOxRjDvzHOMU9kEQt7h3QnDF+IfptqeBM5JMdchIgg3kXxmJQwVTshZpU0CPd7il+l0zt7eFsjaLHBsx5TyLdRZsiJDdUk1CKQLaeBSFL7WctYGRVgSFkULiIQMeiXkxGFHiVxteTY1Nlr2Zf/rLvyZ8OyDK9LSxI4IHzep2YapXjtdjbLtdLoIHSDSGdg/fTudl8JvfAUrtA0if+lrcuXxQRbca9Gd8vP9EXjEu2kYxKDzs=
  skip_cleanup: true
  file:
    - awsweb_linux_amd64
    - awsweb_darwin_amd64
    - awsweb_windows_amd64.exe
  on:
    tags: true
    repo: glassechidna/awsweb