language: go

go:
  - 1.x

install:
  - go get github.com/mitchellh/gox
  - curl -sL -o glide.tgz https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
  - tar -xvf glide.tgz
  - linux-amd64/glide install
  - curl -sL -o upx.txz https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz
  - tar -xvf upx.txz
  
script: gox -arch="amd64" -os="windows linux darwin"

after_success:
  - ls -lh
  - upx-3.93-amd64_linux/upx awsweb_*

deploy:
  provider: releases
  api_key:
    secure: YDvNaVFyi1cq/IiKox5SsBEIznaOD0truWQIQFpetqQFr3/d3tcmLrJ+gaqXAcb5kUbP3NzUo7lTi2IgsFX9KDZA1o4FfcRXQeLmKLUzhEKpe2urbfKSrN66+Vmb+c0VR0PUU1ckhrKQ5mNLQoxcn/vtXxeF87uFNtGE5kGJtgxoVRqIRMMOL4QEH6q2La5laLncK4N4/VmIFFPIpjiuHf/bryGeHzkMjx2eHSLvADQYlRcJX9H4jWgmTBik7ieaSXwpVZwSURFsR167yssTgiyq5w4gFRlU+S9Zeo22KyUXgmtmLioTNDXj4w8FEs6W7JngYFyUMpEfSPvzP8CwuyNI7Bj6vJfy02VZdMbiHK9V2P8Ugm8ce4TuKT7SpZR8GEMjF/fKVcCBiB4GNenvOwqvyWyqoRDMu5OrB23Ca1vgiaSETkDRaZ72ShGqOxRjDvzHOMU9kEQt7h3QnDF+IfptqeBM5JMdchIgg3kXxmJQwVTshZpU0CPd7il+l0zt7eFsjaLHBsx5TyLdRZsiJDdUk1CKQLaeBSFL7WctYGRVgSFkULiIQMeiXkxGFHiVxteTY1Nlr2Zf/rLvyZ8OyDK9LSxI4IHzep2YapXjtdjbLtdLoIHSDSGdg/fTudl8JvfAUrtA0if+lrcuXxQRbca9Gd8vP9EXjEu2kYxKDzs=
  skip_cleanup: true
  file:
    - awsweb_linux_amd64
    - awsweb_darwin_amd64
    - awsweb_windows_amd64.exe
  on:
    tags: true
    repo: glassechidna/awsweb
